# Generated by Django 4.1 on 2022-08-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
