# Generated by Django 4.1 on 2022-08-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thoughts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userthought', to='journal.thought'),
        ),
    ]
