# Generated by Django 4.1 on 2022-08-28 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0007_profile_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thoughts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userthought', to='journal.thought'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
