# Generated by Django 4.1 on 2022-08-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_profile_thoughts_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thoughts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userthought', to='journal.thought'),
        ),
    ]
